---
title: "Assignment1_R"
author: "Tim Hesse"
date: "September 9, 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.0 R version
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

```{r}
# 1.1 Calculate the cube root of 2015
2015^(1/3)

# 1.2 Find the absolute value of 5.7 minus 6.8 divided by .58
abs(5.7-6.8)/.58

# 1.3 Create a list of integers from 1 to 12 and call it “a”
a = 1:12
a

# 1.4 Create a sequence of odd numbers from 1 to 11
b = c(1, 3, 5, 7, 9, 11)
b

# 1.5 Create the same sequence in another way
c = seq(1,11, 2)
c

# 1.6 Take the natural log (ln) of a
ln.a = log(a)
ln.a

# 1.7 Compute the squares of the odd numbers from 1 to 11.
sqrt(b)

# 1.8 Use ?sd to view the help file for the sd function. 
?sd # Open up the help documentation for the std dev function.

# 1.9. Create a variable Name that contains your first name.
Name = "Tim"
paste("My name is", Name)

```

# 1.10 When you shut down R, R will ask if you want to save the workspace image. Always choose no. 
